<?php
/*
 *  Author: Jasper van Doorn
 *  Pagebuilder
 */

if (!defined('ABSPATH')) exit; // Exit if accessed directly

if (function_exists('acf_add_local_field_group')) :

  acf_add_local_field_group(array(
    'key' => 'group_609e73acf3c41',
    'title' => 'Page & Single | Page builder',
    'fields' => array(
      array(
        'key' => 'field_609e8a8983a65',
        'label' => 'Algemene pagina settings',
        'name' => 'pagesettings',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'acfe_seamless_style' => 0,
        'acfe_group_modal' => 0,
        'sub_fields' => array(
          array(
            'key' => 'field_609e8a9883a66',
            'label' => 'Pagina achtergrond',
            'name' => 'page_background',
            'type' => 'color_picker',
            'instructions' => 'Grijs: #F6F6F6, Wit: #FFFFFF, Bruin: #463634, Blauw: #28798A, Oranje: #E96604, Geel: #EDC009',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '#FFFFFF',
          ),
        ),
      ),
      array(
        'acfe_flexible_advanced' => 1,
        'acfe_flexible_stylised_button' => 1,
        'acfe_flexible_hide_empty_message' => 0,
        'acfe_flexible_empty_message' => '',
        'acfe_flexible_disable_ajax_title' => 0,
        'acfe_flexible_layouts_thumbnails' => 1,
        'acfe_flexible_layouts_settings' => 0,
        'acfe_flexible_layouts_ajax' => 1,
        'acfe_flexible_layouts_templates' => 0,
        'acfe_flexible_layouts_previews' => 0,
        'acfe_flexible_layouts_placeholder' => 1,
        'acfe_flexible_title_edition' => 1,
        'acfe_flexible_clone' => 0,
        'acfe_flexible_copy_paste' => 1,
        'acfe_flexible_toggle' => 1,
        'acfe_flexible_close_button' => 1,
        'acfe_flexible_remove_add_button' => 0,
        'acfe_flexible_remove_duplicate_button' => 1,
        'acfe_flexible_remove_delete_button' => 0,
        'acfe_flexible_lock' => 0,
        'acfe_flexible_modal_edition' => 0,
        'acfe_flexible_modal' => array(
          'acfe_flexible_modal_enabled' => '0',
        ),
        'acfe_flexible_layouts_state' => '',
        'acfe_flexible_layouts_remove_collapse' => 0,
        'key' => 'field_609e73b59f507',
        'label' => 'Pagebuilder',
        'name' => 'pagebuilder',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layouts' => array(
          'layout_609e73be0f335' => array(
            'key' => 'layout_609e73be0f335',
            'name' => 'content_fullwidth',
            'label' => 'Wysiwyg',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_609e74189f508',
                'label' => 'Instellingen',
                'name' => 'instellingen',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                  array(
                    'key' => 'field_60ab87e7fxdwsdd',
                    'label' => 'Anchor (om naar te linken met #, voor onpage scroll)',
                    'name' => 'anchor',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '100',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_609e742d9f509',
                    'label' => 'Achtergrond kleur',
                    'name' => 'background_color',
                    'type' => 'color_picker',
                    'instructions' => 'Grijs: #F6F6F6, Wit: #FFFFFF, Donkerpaars: #060424, Groen: #83F480',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '#FFFFFF',
                  ),
                  array(
                    'key' => 'field_609e748a9f50a',
                    'label' => 'Padding top',
                    'name' => 'padding_top',
                    'type' => 'number',
                    'instructions' => 'Ruimte boven het blok',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => 60,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => 'px',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                  ),
                  array(
                    'key' => 'field_609e74a99f50b',
                    'label' => 'Padding bottom',
                    'name' => 'padding_bottom',
                    'type' => 'number',
                    'instructions' => 'Ruimte onderhet blok',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => 60,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => 'px',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                  ),
                ),
              ),
              array(
                'key' => 'field_609e74d09f50c',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                  array(
                    'key' => 'field_60ab87e7d8342dd',
                    'label' => 'Subtitel',
                    'name' => 'subtitel',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '100',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_60ab87e7deeeee',
                    'label' => 'Titel soort',
                    'name' => 'titel_soort',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '25',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'h1' => 'Heading 1',
                      'h2' => 'Heading 2',
                      'h3' => 'Heading 3',
                      'h4' => 'Heading 4',
                    ),
                    'default_value' => false,
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                  ),
                  array(
                    'key' => 'field_60ab87e7dfdfdf',
                    'label' => 'Titel',
                    'name' => 'titel',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '75',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_609e74d69f50d',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'visual',
                    'toolbar' => 'basic',
                    'media_upload' => 1,
                    'delay' => 1,
                  ),
                ),
              ),
            ),
            'min' => '',
            'max' => '',
            'acfe_flexible_thumbnail' => '44',
            'acfe_flexible_category' => false,
            'acfe_flexible_render_template' => false,
            'acfe_flexible_render_style' => false,
            'acfe_flexible_render_script' => false,
            'acfe_flexible_settings' => false,
            'acfe_flexible_settings_size' => 'medium',
          ),
          'layout_609e76aa1c791' => array(
            'key' => 'layout_609e76aa1c791',
            'name' => 'content_left_image_right',
            'label' => 'Wysiwyg - Image',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_609e76e21c792',
                'label' => 'Instellingen',
                'name' => 'instellingen',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                  array(
                    'key' => 'field_60ab87e7fx12sdd',
                    'label' => 'Anchor (om naar te linken met #, voor onpage scroll)',
                    'name' => 'anchor',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '100',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_609e76e31c793',
                    'label' => 'Achtergrond kleur',
                    'name' => 'background_color',
                    'type' => 'color_picker',
                    'instructions' => 'Grijs: #F6F6F6, Wit: #FFFFFF, Donkerpaars: #060424, Groen: #83F480',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '#FFFFFF',
                  ),
                  array(
                    'key' => 'field_609e76e31c794',
                    'label' => 'Padding top',
                    'name' => 'padding_top',
                    'type' => 'number',
                    'instructions' => 'Ruimte boven het blok',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => 60,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => 'px',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                  ),
                  array(
                    'key' => 'field_609e76e31c795',
                    'label' => 'Padding bottom',
                    'name' => 'padding_bottom',
                    'type' => 'number',
                    'instructions' => 'Ruimte onder het blok',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => 60,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => 'px',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                  ),
                ),
              ),
              array(
                'key' => 'field_609e76f31c796',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                  array(
                    'key' => 'field_60ab87e7d8342dd',
                    'label' => 'Subtitel',
                    'name' => 'subtitel',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '100',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_60ab87e7deeeee',
                    'label' => 'Titel soort',
                    'name' => 'titel_soort',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '25',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'h1' => 'Heading 1',
                      'h2' => 'Heading 2',
                      'h3' => 'Heading 3',
                      'h4' => 'Heading 4',
                    ),
                    'default_value' => false,
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                  ),
                  array(
                    'key' => 'field_60ab87e7dfdfdf',
                    'label' => 'Titel',
                    'name' => 'titel',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '75',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_609e77001c797',
                    'label' => 'Wysiwyg',
                    'name' => 'wysiwyg',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                  ),
                  array(
                    'key' => 'field_609e770c1c798',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                    ),
                    'uploader' => 'wp',
                    'acfe_thumbnail' => 0,
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'default_value' => '',
                  ),
                ),
              ),
            ),
            'min' => '',
            'max' => '',
            'acfe_flexible_thumbnail' => '43',
            'acfe_flexible_category' => false,
            'acfe_flexible_render_template' => false,
            'acfe_flexible_render_style' => false,
            'acfe_flexible_render_script' => false,
            'acfe_flexible_settings' => false,
            'acfe_flexible_settings_size' => 'medium',
          ),
          'layout_609e786b648c9' => array(
            'key' => 'layout_609e786b648c9',
            'name' => 'content_right_image_left',
            'label' => 'Image - Wysiwg',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_609e786b648ca',
                'label' => 'Instellingen',
                'name' => 'instellingen',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => '',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'acfe_group_modal_close' => 0,
                'acfe_group_modal_button' => '',
                'acfe_group_modal_size' => 'large',
                'sub_fields' => array(
                  array(
                    'key' => 'field_60ab87e7fx34sdd',
                    'label' => 'Anchor (om naar te linken met #, voor onpage scroll)',
                    'name' => 'anchor',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '100',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_609e786b648cb',
                    'label' => 'Achtergrond kleur',
                    'name' => 'background_color',
                    'type' => 'color_picker',
                    'instructions' => 'Grijs: #F6F6F6, Wit: #FFFFFF, Donkerpaars: #060424, Groen: #83F480',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '#FFFFFF',
                  ),
                  array(
                    'key' => 'field_609e786b648cc',
                    'label' => 'Padding top',
                    'name' => 'padding_top',
                    'type' => 'number',
                    'instructions' => 'Ruimte boven het blok',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => 60,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => 'px',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                  ),
                  array(
                    'key' => 'field_609e786b648cd',
                    'label' => 'Padding bottom',
                    'name' => 'padding_bottom',
                    'type' => 'number',
                    'instructions' => 'Ruimte onderhet blok',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => 60,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => 'px',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                  ),
                ),
              ),
              array(
                'key' => 'field_609e786b648ce',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => '',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                  array(
                    'key' => 'field_60ab87e7d8342dd',
                    'label' => 'Subtitel',
                    'name' => 'subtitel',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '100',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_60ab87e7deeeee',
                    'label' => 'Titel soort',
                    'name' => 'titel_soort',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '25',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'h1' => 'Heading 1',
                      'h2' => 'Heading 2',
                      'h3' => 'Heading 3',
                      'h4' => 'Heading 4',
                    ),
                    'default_value' => false,
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                  ),
                  array(
                    'key' => 'field_60ab87e7dfdfdf',
                    'label' => 'Titel',
                    'name' => 'titel',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '75',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_609e786b648d0',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                    ),
                    'uploader' => 'wp',
                    'acfe_thumbnail' => 0,
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'default_value' => '',
                  ),
                  array(
                    'key' => 'field_609e786b648cf',
                    'label' => 'Wysiwyg',
                    'name' => 'wysiwyg',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                  ),
                ),
              ),
            ),
            'min' => '',
            'max' => '',
            'acfe_flexible_thumbnail' => '42',
            'acfe_flexible_category' => false,
            'acfe_flexible_render_template' => false,
            'acfe_flexible_render_style' => false,
            'acfe_flexible_render_script' => false,
            'acfe_flexible_settings' => false,
            'acfe_flexible_settings_size' => 'medium',
          ),
          'layout_609e7888648d1' => array(
            'key' => 'layout_609e7888648d1',
            'name' => 'image_right_image_left',
            'label' => 'Image - Image',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_609e7888648d2',
                'label' => 'Instellingen',
                'name' => 'instellingen',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => '',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'acfe_group_modal_close' => 0,
                'acfe_group_modal_button' => '',
                'acfe_group_modal_size' => 'large',
                'sub_fields' => array(
                  array(
                    'key' => 'field_60ab87e7fx56sdd',
                    'label' => 'Anchor (om naar te linken met #, voor onpage scroll)',
                    'name' => 'anchor',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '100',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_609e7888648d3',
                    'label' => 'Achtergrond kleur',
                    'name' => 'background_color',
                    'type' => 'color_picker',
                    'instructions' => 'Grijs: #F6F6F6, Wit: #FFFFFF, Donkerpaars: #060424, Groen: #83F480',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '#FFFFFF',
                  ),
                  array(
                    'key' => 'field_609e7888648d4',
                    'label' => 'Padding top',
                    'name' => 'padding_top',
                    'type' => 'number',
                    'instructions' => 'Ruimte boven het blok',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => 60,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => 'px',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                  ),
                  array(
                    'key' => 'field_609e7888648d5',
                    'label' => 'Padding bottom',
                    'name' => 'padding_bottom',
                    'type' => 'number',
                    'instructions' => 'Ruimte onderhet blok',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => 60,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => 'px',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                  ),
                ),
              ),
              array(
                'key' => 'field_609e7888648d6',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => '',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                  array(
                    'key' => 'field_609e7888648d7',
                    'label' => 'Image left',
                    'name' => 'image_left',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                    ),
                    'uploader' => 'wp',
                    'acfe_thumbnail' => 0,
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'default_value' => '',
                  ),
                  array(
                    'key' => 'field_609e7892648d9',
                    'label' => 'Image right',
                    'name' => 'image_right',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                    ),
                    'uploader' => 'wp',
                    'acfe_thumbnail' => 0,
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'default_value' => '',
                  ),
                ),
              ),
            ),
            'min' => '',
            'max' => '',
            'acfe_flexible_thumbnail' => '46',
            'acfe_flexible_category' => false,
            'acfe_flexible_render_template' => false,
            'acfe_flexible_render_style' => false,
            'acfe_flexible_render_script' => false,
            'acfe_flexible_settings' => false,
            'acfe_flexible_settings_size' => 'medium',
          ),
          'layout_609e78b2648da' => array(
            'key' => 'layout_609e78b2648da',
            'name' => 'image_fullwidth',
            'label' => 'Image ',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_609e78b2648db',
                'label' => 'Instellingen',
                'name' => 'instellingen',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => '',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'acfe_group_modal_close' => 0,
                'acfe_group_modal_button' => '',
                'acfe_group_modal_size' => 'large',
                'sub_fields' => array(
                  array(
                    'key' => 'field_60ab87e7fx78sdd',
                    'label' => 'Anchor (om naar te linken met #, voor onpage scroll)',
                    'name' => 'anchor',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '100',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_609e78b2648dc',
                    'label' => 'Achtergrond kleur',
                    'name' => 'background_color',
                    'type' => 'color_picker',
                    'instructions' => 'Grijs: #F6F6F6, Wit: #FFFFFF, Donkerpaars: #060424, Groen: #83F480',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '#FFFFFF',
                  ),
                  array(
                    'key' => 'field_609e78b2648dd',
                    'label' => 'Padding top',
                    'name' => 'padding_top',
                    'type' => 'number',
                    'instructions' => 'Ruimte boven het blok',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => 60,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => 'px',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                  ),
                  array(
                    'key' => 'field_609e78b2648de',
                    'label' => 'Padding bottom',
                    'name' => 'padding_bottom',
                    'type' => 'number',
                    'instructions' => 'Ruimte onderhet blok',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => 60,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => 'px',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                  ),
                  array(
                    'key' => 'field_60a2b1d3cbee6',
                    'label' => 'Margin top',
                    'name' => 'margin_top',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                  ),
                  array(
                    'key' => 'field_60a2b1fecbee7',
                    'label' => 'Margin bottom',
                    'name' => 'margin_bottom',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                  ),
                ),
              ),
              array(
                'key' => 'field_609e78b2648df',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => '',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                  array(
                    'key' => 'field_60a2acc184d63',
                    'label' => 'Volledige breedte',
                    'name' => 'volledige_breedte',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                  ),
                  array(
                    'key' => 'field_60a2acf384d64',
                    'label' => 'Linear gradient background',
                    'name' => 'linear_gradient_background',
                    'type' => 'text',
                    'instructions' => 'Website: https://cssgradient.io/
Voorbeeld: linear-gradient(90deg, rgba(2,0,36,1) 2%, rgba(9,9,121,1) 48%, rgba(0,212,255,1) 100%)',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_609e78b2648e0',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'uploader' => 'wp',
                    'acfe_thumbnail' => 0,
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'default_value' => '',
                  ),
                ),
              ),
            ),
            'min' => '',
            'max' => '',
            'acfe_flexible_thumbnail' => '45',
            'acfe_flexible_category' => false,
            'acfe_flexible_render_template' => false,
            'acfe_flexible_render_style' => false,
            'acfe_flexible_render_script' => false,
            'acfe_flexible_settings' => false,
            'acfe_flexible_settings_size' => 'medium',
          )
        ),
        'button_label' => 'Nieuwe sectie toevoegen',
        'min' => '',
        'max' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'post',
        ),
      ),
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
        ),
        array(
          'param' => 'post_template',
          'operator' => '==',
          'value' => 'default',
        ),
        array(
          'param' => 'page_type',
          'operator' => '!=',
          'value' => 'posts_page',
        ),
        array(
          'param' => 'post_template',
          'operator' => '!=',
          'value' => 'templates/template-aboutus.php',
        ),
        array(
          'param' => 'post_template',
          'operator' => '!=',
          'value' => 'templates/template-projects.php',
        ),
        array(
          'param' => 'post_template',
          'operator' => '!=',
          'value' => 'templates/template-contact.php',
        ),
      )
    ),
    'menu_order' => 100,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'above_field',
    'hide_on_screen' => array(
      0 => 'block_editor',
      1 => 'the_content',
    ),
    'active' => true,
    'description' => '',
    'acfe_display_title' => 'Pagebuilder',
    'acfe_autosync' => array(
      0 => 'json',
    ),
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
  ));

endif;
